// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQN21VPFpPdsdtvH8-d53geuNIH-HU8_U',
    appId: '1:693271942203:web:16547931eec81efcf0b81e',
    messagingSenderId: '693271942203',
    projectId: 'sclad1',
    authDomain: 'sclad1.firebaseapp.com',
    databaseURL: 'https://sclad1-default-rtdb.firebaseio.com',
    storageBucket: 'sclad1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9SBz2EL3t-HfVZje0d4uOE-5Ed-BU0xs',
    appId: '1:693271942203:android:62885cef9eb23209f0b81e',
    messagingSenderId: '693271942203',
    projectId: 'sclad1',
    databaseURL: 'https://sclad1-default-rtdb.firebaseio.com',
    storageBucket: 'sclad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Ita8Sa5IphWoRABAZmwE3NKRaTh6RJQ',
    appId: '1:693271942203:ios:1829234d0ac7e831f0b81e',
    messagingSenderId: '693271942203',
    projectId: 'sclad1',
    databaseURL: 'https://sclad1-default-rtdb.firebaseio.com',
    storageBucket: 'sclad1.appspot.com',
    iosClientId: '693271942203-rd35djj7h8d1nka9178q3q3ot31dklb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFlutProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Ita8Sa5IphWoRABAZmwE3NKRaTh6RJQ',
    appId: '1:693271942203:ios:599bac476164d9abf0b81e',
    messagingSenderId: '693271942203',
    projectId: 'sclad1',
    databaseURL: 'https://sclad1-default-rtdb.firebaseio.com',
    storageBucket: 'sclad1.appspot.com',
    iosClientId: '693271942203-u4bjh4hn44i6iif40trhcp8n9f64kgl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFlutProj.RunnerTests',
  );
}
